name: habit_forge
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
    sdk: ">=3.1.4 <4.0.0"

dependencies:
    drift: ^2.16.0
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter
    intl: ^0.18.1
    path: ^1.8.3
    path_provider: ^2.1.2
    sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
    flutter_test:
        sdk: flutter

    flutter_lints: ^2.0.0
    build_runner: ^2.4.8
    drift_dev: ^2.16.0
    drift_db_viewer: ^2.0.0

flutter:
    uses-material-design: true

    # Enable generation of localized Strings from arb files.
    generate: true

    assets:
        # Add assets from the images directory to the application.
        - assets/images/
